### PR TITLE
Update ru_be_dict.py

### PR DESCRIPTION
**Pull request by alenava**
ru_be_dict.py with Belarusian translation added.

### CODE REVIEW

**Comment by fatalinha** [comment]
Dictionary completed

**Comment by yauhen-info** [comment]
1.  I found that some translations have multiple options because of possible "у"-"ў" change, like
`"включая" : "уключаючы", "ўключаючы" #8542`, which is correct, in my opinion.
But sometimes possible options are not mentioned, like in `"у" : "у" #32016`.
I guess as more consistent the resource, as better.
2. Not sure I'm familiar with a _word_ `"г" : "г" #18736`

**Comment by alenava** [comment]
@YauhenMinsk, I was just about to write to Alina about "у"/"ў".
1. Regarding the options: I doubt I can defend the use of all "ў"-starting variants of the dictionary entries for this task at all. If I were doing this task, I probably wouldn't use them because essentially they comprise once lexical unit that changes the initial vowel, obeying one simple grammar rule of the language. The meaning of the unit certainly remains the same, and  Alina mentions in her readme that the degree of refinement for this ML-task is low (thus I would suppose "у"/"ў" variation could be compromised).

2. This weird entry is caused by preprocessing of the Russian corpus (punctuation strippoff) - "г." = "год" (eng. "year"). I doubt it can be of much use, but I added the translation anyway.

**Comment by fatalinha** [comment]
Hi to both! Thank you so much for your work and your suggestions. 
1. Maybe you can explain a bit more if there is any difference between "у"/"ў" except for the pronunciation. Is there any difference in meaning? Is one of them stylistically better? Is one of them more "accepted" or expected? My model is a character-based model, so I want to try to remove ambiguities in characters as much as possible. In the case of double translations, I will probably either choose one of them or just leave the word as it is in Russian, depending on which approach gives better results. This is why I asked for multiple translations too.
2. So what is the date format in BE? Is "год" used or just omitted? For example how would you translate the following: 13 октября 2009г.

**Comment by alenava** [comment]
Hi,
1. The difference between "у"/"ў": 
in most words (though there are exceptions, say, lexical loans), "у" is replaced by "ў" if this letter follows a vowel. "ў" never occurs after punctuation marks and in the position of the capital letter. "у"/"ў" change doesn't affect texts either stylistically or meaning-wise. 
It's a basic grammar rule, and on the surface its purpose is to reflect the peculiarities of Belarusian phonetics.

2. "год" is used the same way it is used in dates in Russian. "13 октября 2009г." (RU) - "13 кастрычнiка 2009г." (BE)

**Pull request merged**
